### ISSUE TITLE
Should the header be changed?

### ISSUE THREAD

**Issue by sorenss** [ICLC-10/Templates#1]
The header in the template contains the text "ICLC-10 2023 - Document Template for Revised Abstracts" (both Word and LibreOffice formats). Should I keep this in this in the revised abstract? And if not, should I replace it with my name, talk title or something else?

I don't see a place in the text addressing this, and it feels weird to send something marked as "Document Template for Revised Abstracts".

**Comment by kupietz** [comment]
> The header in the template contains the text "ICLC-10 2023 - Document Template for Revised Abstracts" (both Word and LibreOffice formats). Should I keep this in this in the revised abstract? And if not, should I replace it with my name, talk title or something else?
> 
> I don't see a place in the text addressing this, and it feels weird to send something marked as "Document Template for Revised Abstracts".

Don't worry, you can leave them as they are. We will automatically replace the headers once all the documents have been merged. 


Thank you for asking here! You are surely not the only one with this question.

**Comment by sorenss** [comment]
That's great, I'll keep it then. Hope the others find the answer here then!
